stages:
  - lint
  - test
  - build

variables:
  PYTHON_VERSION: "3.11"
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"

default:
  image: python:${PYTHON_VERSION}-slim

cache:
  paths:
    - .cache/pip
    - .venv

before_script:
  - python -V
  - pip install uv
  - uv sync --all-extras
  - source .venv/bin/activate

lint_job:
  stage: lint
  script:
    - uv run ruff check .
    - uv run ruff format --check .
  rules:
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event'
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
    - if: $CI_COMMIT_BRANCH == "feature-final"

babel_job:
  stage: lint
  script:
    - |
      uv run pybabel extract . -o messages.pot --no-creation-date
      if [ -n "$(git status --porcelain messages.pot)" ]; then
        echo "ERROR: messages.pot has changed. Please run 'git add messages.pot' and commit again."
        exit 1
      fi
  rules:
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event'
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
    - if: $CI_COMMIT_BRANCH == "feature-final"

test_job:
  stage: test
  script:
    - uv run pytest tests/
  rules:
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event'
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
    - if: $CI_COMMIT_BRANCH == "feature-final"

mypy:
  stage: test
  script:
    - uv run mypy --config-file mypy.ini .
  rules:
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event'
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
    - if: $CI_COMMIT_BRANCH == "feature-final"

vulture_job:
  stage: test
  script:
    - uv run vulture gitlab_utils/ modes/ Projects/ app.py --min-confidence 100
  rules:
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event'
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
    - if: $CI_COMMIT_BRANCH == "feature-final"

audit_job:
  stage: test
  script:
    - |
      req="0.11.2"
      cur=$(uv --version | cut -d" " -f2)
      if [ "$(printf "%s\n%s" "$req" "$cur" | sort -V | head -n1)" != "$req" ]; then
        echo "ERROR: uv v$cur is installed, but v$req or higher is required."
        exit 1
      fi
    - uv audit
  rules:
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event'
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
    - if: $CI_COMMIT_BRANCH == "feature-final"

build_job:
  stage: build
  script:
    - uv build
  artifacts:
    paths:
      - dist/
  rules:
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event'
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
    - if: $CI_COMMIT_BRANCH == "feature-final"
